---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "${K8S_NAME}"
  namespace: "${K8S_NAMESPACE}"
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: "${K8S_NAME}"
  namespace: "${K8S_NAMESPACE}"
  labels:
    k8s-app: "${K8S_APP}"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: "${K8S_APP}"
  template:
    metadata:
      labels:
        k8s-app: "${K8S_APP}"
        name: "${K8S_APP}"
    spec:
      serviceAccountName: "${K8S_NAME}"
      terminationGracePeriodSeconds: 60
      containers:
      - image: "${TRAEFIK_IMAGE}:${TRAEFIK_VERSION}"
        name: "${K8S_APP}"
        resources:
          limits:
            cpu: 200m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 30Mi
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        - name: admin
          containerPort: 8080
        args:
        - --kubernetes
        - --configFile=/etc/traefik/traefik.toml
        volumeMounts:
        - name: traefik-config
          mountPath: /etc/traefik
        - name: traefik-volume
          mountPath: /data/traefik
        - name: traefik-ssl
          mountPath: /etc/tls
      volumes:
      - name: traefik-config
        configMap:
          name: traefik-config
          items:
          - key: traefik.toml
            path: traefik.toml
      - name: traefik-volume
        persistentVolumeClaim:
          claimName: traefik-volume
      - name: traefik-ssl
        secret:
          secretName: traefik-ssl
