---
kind: Service
apiVersion: v1
metadata:
  name: "${K8S_NAME}"
  namespace: "${K8S_NAMESPACE}"
  labels:
    k8s-app: "${K8S_APP}"
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal: "${K8S_INTERNAL_LB}"
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
