kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: slow
 namespace: "${K8S_NAMESPACE}"
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Shared
