kind: PersistentVolumeClaim

apiVersion: v1
metadata:
  name: traefik-volume
  namespace: "${K8S_NAMESPACE}"
  annotations:
    volume.beta.kubernetes.io/storage-class: "${K8S_DISK_TYPE}"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
