kind: PersistentVolumeClaim

apiVersion: v1
metadata:
  name: traefik-volume
  namespace: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
